num_class: 2
batch_size: 128
input_adapter_params: {'type': 'TextInputAdapter',
                       'vocab_size': 40001,
                       'max_seq_len': 512,
                       'num_input_channels' : 50}
output_adapter_params: {'type' : 'TextOutputAdapter',
                       'vocab_size': 40001,
                       'max_seq_len': 512,
                       'num_output_channels': 2}


num_self_heads: 4
num_cross_heads: 4
qlatent_dim: 256
qout_dim: 256
q_length: 256
qout_length: 128
num_latent_blocks: 2
dropout_prob: 0.0
optim_params: {'type': 'Adam',
              'lr' : 0.001}
name: 'Test0'
max_epochs: 120