data_dir: '/content/tiny-imagenet-200'
num_class: 200
batch_size: 64
image_shape: 64
input_adapter_params: {'type': 'ImageInputAdapter',
                       'image_shape': [64, 64, 3],
                       'num_frequency_bands' : 128}
output_adapter_params: {'type' : 'ImageClassificationAdapter',
                       'qout_dim': 1024,
                       'num_class': 200}
num_self_heads: 8
num_cross_heads: 1
qlatent_dim: 256
q_length: 256
qout_length: 64
qout_dim: 1024
num_latent_blocks: 1
dropout_prob: 0.0
optim_params: {'type': 'Adam',
              'lr' : 0.0001}
name: 'Final'
max_epochs: 120
num_workers: 2
tie_weights: True
num_self_layers: 3
