data_dir: '/content/tiny-imagenet-200'
num_class: 100000
batch_size: 32
image_shape: 64
input_adapter_params: {'type': 'ImageInputAdapter',
                       'image_shape': [64, 64,3],
                       'num_frequency_bands' : 64}
output_adapter_params: {'type' : 'ImageClassificationAdapter',
                       'qout_dim': 128,
                       'num_class': 100000}
num_self_heads: 4
num_cross_heads: 4
qlatent_dim: 256
qout_dim: 128
q_length: 128
qout_length: 32
num_latent_blocks: 8
dropout_prob: 0.1
optim_params: {'type': 'Adam',
              'lr' : 0.001}
name: 'Test0'
max_epochs: 120
num_workers: 2
