num_class: 10
batch_size: 32
image_shape: [28,28,1]
input_adapter_params: {'type': 'ImageInputAdapter',
                       'image_shape': [28,28,1],
                       'num_frequency_bands' : 64}
output_adapter_params: {'type' : 'ImageClassificationAdapter',
                       'qout_dim': 256,
                       'num_class': 10}
num_self_heads: 4
num_cross_heads: 4
qlatent_dim: 256
qout_dim: 256
q_length: 256
qout_length: 128
num_latent_blocks: 2
dropout_prob: 0.0
optim_params: {'type': 'Adam',
              'lr' : 0.001}
name: 'Test0'
max_epochs: 120